### ISSUE TITLE
Been thinking about the knex event emitter

### ISSUE THREAD

**Issue by tgriesser** [bendrucker/emit-then#1]
What do you think about an emit-then pattern for the knex event-emitter, where it'd be possible to hook into events and return a promise to help solve one of the hard problems of cache invalidation:

``` js
knex.on('query', function(data) {
   // some invalidation here based on examining the contents of data,
   // running the query when any returned promises resolve.
});
```

Presumably if everything in an app runs through knex, this would actually make cache-invalidation feasible.

Also, unrelated, but I've been thinking more around the semantics of the registry, and I think it'd actually be good to specify a "resolver" method, where you could specify where models are cached & resolved from/to, where the default behavior would be to act as it does now.

``` js
bookshelf.registry.resolver = function(modelName) {
   return app.get(modelName);
};
```

**Comment by bendrucker** [comment]
Definitely a :thumbsup: on that. Tough part is offering the ability to both modify things pre-query (via emit-then) and post-query (via promise handlers). So I'd want knex to emit the actual query instance.

For example:

``` js
knex.on('query', function (query) {
  var timestamps = {};
  timestamps.invalidation = Date.now();
  return invalidateCached(query)
    .then(function () {
      timestamps.query_start = Date.now();
      return query;
    })
    .finally(function () {
      timestamps.query_end = Date.now();
      log.track('query', timestamps);
    });
});
```

Gets a little weird and probably really confusing. But it should allow for basically any control flow you could possibly want on a query. 

Re bookshelf registry, I'm with you. If someone's using a framework and wants to use its config/storage system vs. calling `require` that should definitely be supported.
